import Head from 'next/head';
import Navbar from './Navbar';
import styles from '../styles/Layout.module.css';

const Layout = ({ children }) => {
  return (
    // Layout.module.css dosyasinda henuz tanimlanmis stil yok.
    <>
      <Head>
        <title>Av. Beytullah Murat | Murat Hukuk ve Danışmanlık</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.container}>
        <main className={styles.main}>
          {children}
        </main>
      </div>
    </>
  )
}

export default Layout
